from abc import ABC, abstractmethod
from typing import List, Optional
from app.domain.entities import FlowerCreate, FlowerOut, FlowerUpdate

class FlowerRepository(ABC):
    @abstractmethod
    async def create(self, flower: FlowerCreate) -> FlowerOut: ...
    @abstractmethod
    async def list(self) -> List[FlowerOut]: ...
    @abstractmethod
    async def get(self, flower_id: str) -> Optional[FlowerOut]: ...
    @abstractmethod
    async def update(self, flower_id: str, flower: FlowerUpdate) -> Optional[FlowerOut]: ...
    @abstractmethod
    async def delete(self, flower_id: str) -> bool: ...
